#!/usr/bin/env python
import argparse
import json
import requests
from pprint import pprint


def get_access_token(user, password):
    r = requests.post(
        "http://localhost:8083/realms/auth2/protocol/openid-connect/token",
        data={
            "client_id": "auth2",
            "grant_type": "password",
            "username": user,
            "password": password,
        },
    )
    r.raise_for_status()
    return r.json()["access_token"]


def call_api(method, route, data=None, access_token=None):
    headers = None
    if access_token:
        headers = {"Authorization": f"Bearer {access_token}"}
    r = requests.request(
        method, f"http://localhost:8082/{route}", data=data, headers=headers
    )
    r.raise_for_status()
    return r.json()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-u", "--user")
    parser.add_argument("-p", "--password")
    parser.add_argument("-t", "--token", action="store_true")
    parser.add_argument("method")
    parser.add_argument("route")
    parser.add_argument("data", nargs="?")
    args = parser.parse_args()

    access_token = None
    if args.user:
        access_token = get_access_token(args.user, args.password or args.user)
        if args.token:
            print(f"access token: {access_token}")
    data = None
    if args.data:
        data = json.loads(args.data)
    result = call_api(args.method, args.route, data=data, access_token=access_token)
    pprint(result)