#!/usr/bin/env python
import argparse
import json
import requests
from pprint import pprint


def login(username, password):
    r = requests.post(
        "http://localhost:8082/rpc/login",
        data={
            "username": username,
            "password": password,
        },
    )
    try:
        r.raise_for_status()
    except Exception:
        pprint(r.json())
        raise
    return r.json()


def call_api(method, route, data=None, access_token=None):
    headers = None
    if access_token:
        headers = {"Authorization": f"Bearer {access_token}"}
    r = requests.request(
        method, f"http://localhost:8082/{route}", data=data, headers=headers
    )
    try:
        r.raise_for_status()
    except Exception:
        pprint(r.json())
        raise
    return r.json()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-u", "--user")
    parser.add_argument("-p", "--password")
    parser.add_argument("-t", "--token", action="store_true")
    parser.add_argument("method")
    parser.add_argument("route")
    parser.add_argument("data", nargs="?")
    args = parser.parse_args()

    access_token = None
    if args.user:
        login_info = login(args.user, args.password or args.user)
        access_token = login_info["access_token"]
        if args.token:
            print(f"Authorization: Bearer {access_token}")
    data = None
    if args.data:
        data = json.loads(args.data)
    result = call_api(
        args.method,
        args.route,
        data=data,
        access_token=access_token,
    )
    pprint(result)
