services:
  postgres:
    build:
      context: .
      dockerfile_inline: |
        FROM postgres:17.4
        RUN apt update && apt install python3 python3-pip postgresql-plpython3-17 python3-requests -y
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh
      - ./python:/usr/lib/n4b_auth/python
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      KEYCLOAK_DB: ${KEYCLOAK_DB}
      KEYCLOAK_DB_USER: ${KEYCLOAK_DB_USER}
      N4B_AUTH_DB: ${N4B_AUTH_DB}
      PYTHONPATH: /usr/lib/n4b_auth/python
    secrets:
      - source: postgres-password
        mode: 0600
      - source: keycloak-db-password
        uid: "999"
        mode: 0600
      - source: n4b_auth_authenticator-password
        uid: "999"
        mode: 0600
    networks:
      - n4b_auth_network

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4-secret  ; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgadmin4-secret
        target: /pgadmin4-secret
    ports:
      - 8081:80
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - n4b_auth_network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://127.0.0.1:8082/
    networks:
      - n4b_auth_network

  postgrest:
    image: postgrest/postgrest
    ports:
      - 8082:8082
    secrets:
      - n4b_auth-jwt-secret
    configs:
      - source: n4b_auth-db-passfile
        target: /run/secrets/n4b_auth-db-passfile
        mode: 0600
    environment:
      N4B_AUTH_DB: ${N4B_AUTH_DB}
      PGRST_DB_URI: postgres://n4b_auth_authenticator:${N4B_AUTH_AUTHENTICATOR_PASSWORD}@postgres:5432/${N4B_AUTH_DB}
      PGRST_SERVER_PORT: 8082
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:8082
      PGRST_OPENAPI_SECURITY_ACTIVE: "true"
      PGRST_OPENAPI_MODE: ignore-privileges
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: n4b_auth_anonymous
      # PGRST_JWT_SECRET: "@/run/secrets/n4b_auth-jwt-secret"
      PGRST_JWT_SECRET: '{"kid":"BJledsHD8gTXv2nlYMdppyT4nYPS47UhkHbp2RRBOJM","kty":"RSA","alg":"RS256","n":"okuvx-UF8qXHnpcJRkz707t1S2NmnsLStqtB1_MIdwz6Sv33-9CjgNcTnZEk1ZHglKchyDLc0GbZG3UR9YPXdTK5845kg-EEA_JQS6MlSpDhQznQemW-IlJdxuZWfwc4QKaMdHtPGoLdzUiDEESYfQ3apFqNosodSe-K-g0HjP1322bshs222Ur6u6tDk_n-EceHYqMBlRpDg0xQYTEcrx4HN_wTSe_uxCjrwA23LdV5Tn9qSTa9Ci1-1d8yFSiWWkN19av9qKHBepNrT_nvvkCmVwVXe_KmC4flWxZbteKuwp9yhkEaHgt2evCvvp28y0VQl2Y1qsHbOfATSv-fUw","e":"AQAB"}'
      PGRST_JWT_ROLE_CLAIM_KEY: ".preferred_username"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - n4b_auth_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    command: start --import-realm
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8083
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD_FILE: /run/secrets/keycloak-db-password
      # Password is also contained in the file above that is used by keycloak
      #but it is required to create the role (i.e user) in the database 
      # initialization script
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ./keycloak-import:/opt/keycloak/data/import:rw
    secrets:
      - keycloak-db-password
    ports:
      - 8083:8080
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - n4b_auth_network

secrets:
  postgres-password:
    environment: POSTGRES_PASSWORD
  keycloak-db-password:
    environment: KEYCLOAK_DB_PASSWORD
  n4b_auth_authenticator-password:
    environment: N4B_AUTH_AUTHENTICATOR_PASSWORD
  n4b_auth-jwt-secret:
    environment: N4B_AUTH_JWT_SECRET

configs:
  pgadmin4-secret:
    content: postgres:5432:*:postgres:${POSTGRES_PASSWORD}
  n4b_auth-db-passfile:
    content: postgres:5432:${N4B_AUTH_DB}:n4b_auth_authenticator:${N4B_AUTH_AUTHENTICATOR_PASSWORD}
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "N4Brain",
        "Host": "postgres",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "postgres",
        "PassFile": "/pgadmin4-secret",
        "SSLMode": "prefer"
      }}}

volumes:
  postgres_data:
    driver: local

networks:
  n4b_auth_network:
    driver: bridge


