#!/bin/sh
curl -s http://localhost:8083/realms/auth2/protocol/openid-connect/certs | jq -rc '.keys[] | select(.alg=="RS256") | {kid, kty, alg, n, e}' | awk '{print("PGRST_JWT_SECRET: '\''" $0 "'\''")}'
