[project]
authors = ["sapetnioc <sapetnioc@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "keycloak"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
docker-compose = ">=2.33.0,<3"
